# Vectores, listas y matrices#

El objeto más básico en R es un **vector**, que se puede definir como un conjunto de elementos del mismo tipo. Creamos vectores usando la función **c**, abreviatura de **concatenate**. Para crear vectores de tipo "character" debemos usar dobles comillas. En caso contrario R pensará que son variables y usará su valor si es que este existe.

In [2]:
x <- vector() # vector vacio
x <- vector ("numeric", lenght=10) # vector vacio de longitud 10
x <- c(380, 124, 818)
x <- c("italia", "canada", "egipto")
x <- c(TRUE, FALSE) # vector valores logicos
x <- c(T,F,T) # vector valores logicos
x <- 1:10
x <- c(2+3i, 1+2i) # vector de valores complejos

Los elementos de un vector han de ser de uno de los tipos básicos en R: valores numéricos enteros, decimales, caracter y lógicos (integer, numeric,character, logic). La función **class** nos devuelve el tipo 

In [4]:
x <- vector()
y <- c(380, 124, 818)
z <- c("italia", "canada", "egipto")
class(x)
class(y)
class(z)

[1] "logical"

[1] "numeric"

[1] "character"

Otra manera de crear vectores numericos es definiendo nombres para cada uno de ellos. No estamos asignando variables sino etiquetando los valores. Aunque estas etiquetas forman parte del vector, sigue siendo de tipo numérico

In [2]:
codes <- c(italia=380, canada=124, egipto=818)
# codes <- c("italia"=380, "canada"=124, "egipto"=818) da el mismo resultado!
codes
class(codes)

italia canada egipto 
   380    124    818

[1] "numeric"

otra manera de hacer esto

In [3]:
codes <- c(380, 124, 818)
country <- c("italia", "canada", "egipto")
names (codes) <- country
codes

italia canada egipto 
   380    124    818

Otra forma de crear un vector numérico es mediante la función **seq**, abreviatura de **sequence**. **seq** genera una secuencia

In [29]:
seq (1,10) # crea una secuencia de valores numericos del 1 al 10
seq (1,10, 2) # crea una secuencia con un intervalo  = 2
1:10 # equivale a seq (1,10)
seq (1,10,0.5) # genera una secuencia de valores espaciadoso 0.5 unidades
seq(0,100, length.out =5) # genera una secuencia de longitud 5

[1]  1  2  3  4  5  6  7  8  9 10

[1] 1 3 5 7 9

[1]  1  2  3  4  5  6  7  8  9 10

[1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0

[1]   0  25  50  75 100

In [3]:
x <- vector("numeric", 10) # crea un vector de tipo numerico, con valores igual a cero y longitud 10
x

[1] 0 0 0 0 0 0 0 0 0 0

## Conversión de tipos (Vector Coercion) ##

R convierte automáticamente los tipos si intentamos crear un vector con objetos de distinta clase

In [13]:
x <- c(1, "manzanas", 3)
x
class (x)

[1] "1"        "manzanas" "3"

[1] "character"

También podemos forzar el tipo de datos usando **as.character** para convertir a tipo texto o **as.numeric** para convertir a tipo numérico

In [1]:
x <- as.character(0:5)
y <- as.numeric(x)
z <- as.logical (y)

Intentar forzar ciertos valores devuelve como resultado el valor NA

In [4]:
x <- c("a", "b", "c")
y <- as.numeric(x)
y

Warning message in eval(expr, envir, enclos):
"NAs introducidos por coerción"

[1] NA NA NA

In [18]:
x <- c("1", "b", "3")
y <- as.numeric(x)
y

Warning message in eval(expr, envir, enclos):
"NAs introducidos por coerción"

[1]  1 NA  3

## Listas ##

Las listas son un tipo especial de vector que permite elementos de distinto tipo

In [6]:
x <- list ("x", 5+3i, TRUE)
x

[[1]]
[1] "x"

[[2]]
[1] 5+3i

[[3]]
[1] TRUE

Las listas también pueden usar valores con nombres

In [8]:
x <- list(a =1, b=2, c=3)
x

$a
[1] 1

$b
[1] 2

$c
[1] 3

## Matrices ##

Las matrices son vectores con un atributo dimensional

In [10]:
m <- matrix(nrow=2, ncol=3)
dim(m)
m

[1] 2 3

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

Podemos crear matrices a partir de un vector, definiendo el atributo dimensión mediante otro vector

In [14]:
m <- 1:10
m
dim(m) <- c(2,5) # dimension
m

[1]  1  2  3  4  5  6  7  8  9 10

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

***cbind()***, ***rbind()*** permiten 

In [16]:
x <- 1:3
y <- 10:12
cbind(x,y)
rbind(x,y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

Las matrices también pueden tener nombres

In [10]:
m <- matrix(1:4, nrow = 2, ncol=2)
dimnames(m) <- list(c("a", "b"), c("c", "d"))
m

c d
a 1 3
b 2 4

## Factors ##

Los vectores que usan objetos tipo factor se usan para representar categorias de datos. Se puede decir que un factor es un vector de valores integrales con etiquetas, como se puede ver usando el comando **unclass**

In [23]:
x <- factor(c("si", "no", "no", "si", "si"))
x
class(x)
table(x)
unclass(x)

[1] si no no si si
Levels: no si

[1] "factor"

x
no si 
 2  3 

[1] 2 1 1 2 2
attr(,"levels")
[1] "no" "si"

## NA - Not Available y NaN - Not a Number##

El valor NA o NaN puede aparecer en un vector cuando no se carece de ese dato. Este valor puede aparecer como resultado de una operación anterior. **is.na()** y **is.nan()** se usan para determinar si un vector contiene alguno de estos valores.

In [23]:
x <- c(1, 2, NA, 4, 5, NA, 7)
is.na(x) # devuelve un vector indicando si un valor es NA (TRUE)
sum (is.na(x)) # devuelve el total de valores NA

[1] FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE

[1] 2

### Eliminando los valores NA ###

In [25]:
x <- c(1, 2, NA, 4, 5, NA, 7)
mean(x) # no es posible calcular la media con valores NA
ind <- is.na(x)
x <- x[!ind] # creamos un nuevo vector sin los valores NA
x
mean (x) # ahora sí podemos calcular la media

[1] NA

[1] 1 2 4 5 7

[1] 3.8

## sort, order, rank##

Orange es un dataset incluido en R con datos experimentales sobre el diametro de las naranjas

In [31]:
head(Orange)

Tree age  circumference
1 1     118  30          
2 1     484  58          
3 1     664  87          
4 1    1004 115          
5 1    1231 120          
6 1    1372 142

In [2]:
head(Orange$circumference) # nos devuelve un vector cuyos valores tienen el mismo orden que el dataset

[1]  30  58  87 115 120 142

In [33]:
sort(Orange$circumference) # devuelve el vector ordenado de menor a mayor

[1]  30  30  30  32  33  49  51  58  62  69  75  81  87 108 111 112 115 115 120
[20] 125 139 140 142 142 145 156 167 172 174 177 179 203 203 209 214

In [34]:
order(Orange$circumference) # devuelve el indice que pondría el vector en orden (utilizando sort)

[1]  1 15 29 22  8 30 16  2 23  9 17 31  3 18 10 24  4 19  5 32 20 21  6 33  7
[26] 11 25 12 34 35 26 13 14 27 28

In [36]:
index <- order(Orange$circumference)
x <- Orange$circumference
x[index]

[1]  30  30  30  32  33  49  51  58  62  69  75  81  87 108 111 112 115 115 120
[20] 125 139 140 142 142 145 156 167 172 174 177 179 203 203 209 214

Esto no permite ordenar un vector según el indice de otro.

In [4]:
index <- order (Orange$circumference)
Orange$age[index]

[1]  118  118  118  118  118  484  484  484  484  484  664  664  664 1004  664
[16]  664 1004 1231 1231 1004 1372 1582 1372 1231 1582 1004 1004 1231 1372 1582
[31] 1231 1372 1582 1372 1582

**max** y **which.max** nos dan el máximo valor de un vector y su indice. **min** y **which.min** el m enor

In [8]:
max(Orange$circumference)
i_max <- which.max(Orange$circumference)
Orange$age[i_max]

[1] 214

[1] 1582

In [9]:
min(Orange$circumference)
i_min <- which.min(Orange$circumference)
Orange$age[i_min]

[1] 30

[1] 118

**rank** nos devuelve un vector con los indices

In [2]:
x <- c (31, 4, 15, 92, 65)
rank (x) # devuelve un vector con los indices que ordenarían el vector de menor a mayor.
rank (-x) # igual pero ordenado de mayor a menor

[1] 3 1 2 5 4

[1] 3 5 4 1 2

Resumiendo:

In [14]:
x
sort(x)# ordena el vector
order(x) # indices para ordenar el vector original
rank(x) # posición que ocuparían los valores si el vector estuviera ordenado

[1] 31  4 15 92 65

[1]  4 15 31 65 92

[1] 2 3 1 5 4

[1] 3 1 2 5 4

## Aritmética de vectores ##

Las operaciones aritméticas entre vectores se producen elemento por elemento

In [3]:
inches <- c(11, 14, 15.4, 17, 19, 21, 24, 40)
cm = inches*2.54 # multiplica cada elemento del vector por 2.54
cm

[1]  27.940  35.560  39.116  43.180  48.260  53.340  60.960 101.600

In [13]:
pais <- c('España', 'Francia', 'UK', 'Alemania', 'Italia')
sup <- c(505370, 643801, 243610, 357022, 301340) # fuente wikipedia; en km2
hab <- c(46468102, 64995000, 65648100, 82800000, 60525277) # fuente wikipedia; censo 2016-2017
datos_pais <- data.frame(nombre=pais, superficie=sup, habitantes=hab)
datos_pais$habitantes/datos_pais$superficie # densidad de población en habitantes por km2

[1]  91.94868 100.95511 269.48032 231.91848 200.85378

In [14]:
x <- seq(1:100)
sum(1/x^2) # suma de euler; resultado es aproximadamente pi^2/6

[1] 1.634984